services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/user/app:cached
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/dev"

volumes:
    bundle:
